# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/communicate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import base_pb2 as proto_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/communicate.proto',
  package='communicate',
  syntax='proto3',
  serialized_pb=_b('\n\x17proto/communicate.proto\x12\x0b\x63ommunicate\x1a\x10proto/base.proto\"\xc5\x01\n\rCommunication\x12.\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x18.communicate.MessageType\x12\x16\n\x03job\x18\x02 \x03(\x0b\x32\t.base.Job\x12\x1e\n\x07logging\x18\x03 \x01(\x0b\x32\r.base.Logging\x12\x14\n\x0corganization\x18\x04 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x05 \x01(\t\x12\x1e\n\x03\x65nv\x18\x06 \x01(\x0e\x32\x11.base.ENVRIONMENT*\\\n\x0bMessageType\x12\r\n\tSTATEMENT\x10\x00\x12\x0c\n\x08REMINDER\x10\x01\x12\x11\n\rFINALREMINDER\x10\x02\x12\x11\n\rPASSWORDRESET\x10\x03\x12\n\n\x06SIGNUP\x10\x04\x62\x06proto3')
  ,
  dependencies=[proto_dot_base__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='communicate.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATEMENT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMINDER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINALREMINDER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASSWORDRESET', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGNUP', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=258,
  serialized_end=350,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
STATEMENT = 0
REMINDER = 1
FINALREMINDER = 2
PASSWORDRESET = 3
SIGNUP = 4



_COMMUNICATION = _descriptor.Descriptor(
  name='Communication',
  full_name='communicate.Communication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='communicate.Communication.message_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job', full_name='communicate.Communication.job', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logging', full_name='communicate.Communication.logging', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='organization', full_name='communicate.Communication.organization', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_number', full_name='communicate.Communication.account_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='env', full_name='communicate.Communication.env', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=256,
)

_COMMUNICATION.fields_by_name['message_type'].enum_type = _MESSAGETYPE
_COMMUNICATION.fields_by_name['job'].message_type = proto_dot_base__pb2._JOB
_COMMUNICATION.fields_by_name['logging'].message_type = proto_dot_base__pb2._LOGGING
_COMMUNICATION.fields_by_name['env'].enum_type = proto_dot_base__pb2._ENVRIONMENT
DESCRIPTOR.message_types_by_name['Communication'] = _COMMUNICATION
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE

Communication = _reflection.GeneratedProtocolMessageType('Communication', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNICATION,
  __module__ = 'proto.communicate_pb2'
  # @@protoc_insertion_point(class_scope:communicate.Communication)
  ))
_sym_db.RegisterMessage(Communication)


# @@protoc_insertion_point(module_scope)
