# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communicate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communicate.proto',
  package='communicate',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x63ommunicate.proto\x12\x0b\x63ommunicate\"E\n\x03Job\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\x03\x12\x10\n\x08\x63omleted\x18\x04 \x01(\x08\"<\n\x07Logging\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x13\n\x0bother_stuff\x18\x03 \x01(\t\"\xda\x01\n\rCommunication\x12.\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x18.communicate.MessageType\x12\x1d\n\x03job\x18\x02 \x03(\x0b\x32\x10.communicate.Job\x12%\n\x07logging\x18\x03 \x01(\x0b\x32\x14.communicate.Logging\x12\x14\n\x0corganization\x18\x04 \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x05 \x01(\t\x12%\n\x03\x65nv\x18\x06 \x01(\x0e\x32\x18.communicate.ENVRIONMENT*\\\n\x0bMessageType\x12\r\n\tSTATEMENT\x10\x00\x12\x0c\n\x08REMINDER\x10\x01\x12\x11\n\rFINALREMINDER\x10\x02\x12\x11\n\rPASSWORDRESET\x10\x03\x12\n\n\x06SIGNUP\x10\x04*<\n\x0b\x45NVRIONMENT\x12\x0e\n\nPRODUCTION\x10\x00\x12\x0f\n\x0b\x44\x45VELOPMENT\x10\x01\x12\x0c\n\x08STAGEING\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='communicate.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATEMENT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMINDER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINALREMINDER', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASSWORDRESET', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGNUP', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=388,
  serialized_end=480,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_ENVRIONMENT = _descriptor.EnumDescriptor(
  name='ENVRIONMENT',
  full_name='communicate.ENVRIONMENT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRODUCTION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVELOPMENT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STAGEING', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=482,
  serialized_end=542,
)
_sym_db.RegisterEnumDescriptor(_ENVRIONMENT)

ENVRIONMENT = enum_type_wrapper.EnumTypeWrapper(_ENVRIONMENT)
STATEMENT = 0
REMINDER = 1
FINALREMINDER = 2
PASSWORDRESET = 3
SIGNUP = 4
PRODUCTION = 0
DEVELOPMENT = 1
STAGEING = 2



_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='communicate.Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='communicate.Job.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errors', full_name='communicate.Job.errors', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='communicate.Job.job_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comleted', full_name='communicate.Job.comleted', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=103,
)


_LOGGING = _descriptor.Descriptor(
  name='Logging',
  full_name='communicate.Logging',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='communicate.Logging.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sender', full_name='communicate.Logging.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='other_stuff', full_name='communicate.Logging.other_stuff', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=165,
)


_COMMUNICATION = _descriptor.Descriptor(
  name='Communication',
  full_name='communicate.Communication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='communicate.Communication.message_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='job', full_name='communicate.Communication.job', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logging', full_name='communicate.Communication.logging', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='organization', full_name='communicate.Communication.organization', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_number', full_name='communicate.Communication.account_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='env', full_name='communicate.Communication.env', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=386,
)

_COMMUNICATION.fields_by_name['message_type'].enum_type = _MESSAGETYPE
_COMMUNICATION.fields_by_name['job'].message_type = _JOB
_COMMUNICATION.fields_by_name['logging'].message_type = _LOGGING
_COMMUNICATION.fields_by_name['env'].enum_type = _ENVRIONMENT
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['Logging'] = _LOGGING
DESCRIPTOR.message_types_by_name['Communication'] = _COMMUNICATION
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
DESCRIPTOR.enum_types_by_name['ENVRIONMENT'] = _ENVRIONMENT

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), dict(
  DESCRIPTOR = _JOB,
  __module__ = 'communicate_pb2'
  # @@protoc_insertion_point(class_scope:communicate.Job)
  ))
_sym_db.RegisterMessage(Job)

Logging = _reflection.GeneratedProtocolMessageType('Logging', (_message.Message,), dict(
  DESCRIPTOR = _LOGGING,
  __module__ = 'communicate_pb2'
  # @@protoc_insertion_point(class_scope:communicate.Logging)
  ))
_sym_db.RegisterMessage(Logging)

Communication = _reflection.GeneratedProtocolMessageType('Communication', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNICATION,
  __module__ = 'communicate_pb2'
  # @@protoc_insertion_point(class_scope:communicate.Communication)
  ))
_sym_db.RegisterMessage(Communication)


# @@protoc_insertion_point(module_scope)
